### ISSUE TITLE
Motion Sensors don’t send motion 

### ISSUE THREAD

**Issue by HouseGMoney** [balansse/homebridge-vivint#15]
Hello,

Thank you for this very helpful project. I was able to get all Vivint sensors into HomeKit but the motion sensors do not seem to identify when motion has occurred. I cannot see motion triggered in HomeKit when it should be triggered and cannot use them in motion-based automations. 

Thanks in advance for your help!

**Comment by balansse** [comment]
Could you please check the log file for any warnings from the Vivint plugin?

**Comment by HouseGMoney** [comment]
Hello,

I'm unable to see my logs beyond today but nothing from Vivint today. Is
there a way to pull older logs?

Thanks.

**Comment by HouseGMoney** [comment]
Reset today and there are no warnings in the log steps on Vivint.

**Comment by balansse** [comment]
Yesterday I set up a push notification for motion sensor to test it out and looks like it is working as it should. 

What model does HomeKit show for your Motion Detector?

**Comment by HouseGMoney** [comment]
I noticed the the older motion sensors don’t seem to work but the newer
ones do. This particular one says EXISTING_MOTION_SENSOR

**Comment by balansse** [comment]
This might be because Vivint API handles these old sensors differently. Unfortunately, I don't have access to all the device combinations, so I would need some assistance.

Could you [run the HomeBridge in Debug mode](https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#debug-mode), trigger the problematic sensor a couple of times, and send me the complete log of that session? I need to see what data is sent to make sure the plugin is reading the right one.

**Comment by balansse** [comment]
I just released 1.5.0, please check it out and let me know!
