### ISSUE TITLE
Feature request - Pre-Alarm and Alarm devices/contacts

### ISSUE THREAD

**Issue by chrismortega** [balansse/homebridge-vivint#155]
Not sure if this is do-able but I’d love to be able to trigger flashing lights etc during alarm conditions. There doesn’t seem to currently be any device indicating those conditions.

**Comment by jgrimard** [comment]
I have a smart plug linked directly to my Vivint Hub.  In the Vivint app, you can trigger the outlet to turn on when the alarm triggers.  You could use Homekit to trigger an automation any time that outlet turns on.  Just a thought.  I'm not sure if there is any way to add a fake outlet or create any sort of fake alarm output to use as a trigger.

**Comment by chrismortega** [comment]
Nice - I’ll give this a shot - thanks!

**Comment by jgrimard** [comment]
Actually, I take that back.  Homekit should already know if the alarm is triggered.  I see it in the source code.  Try creating a "automation" in Homekit.  Select Events: An Accessory is Controlled.  Then select Security System and click next.  Then select "Triggers" from the list and click next.  You should then be able to use this to control lights or set up a more elaborate automation that turns lights on and off in a loop.  I can't test it now since the family is here and I don't really want to set of the alarm.  Let me know if this works though.

**Comment by chrismortega** [comment]
Oh wow - you’re absolutely right! I am a little nervous to test it also, but def looks like it would work. Thanks for looking into this for me! Feel free to close the issue.

![IMG_2530](https://github.com/user-attachments/assets/a247ab76-a2fd-46a4-89bf-6fd5779761dc)
