### ISSUE TITLE
Constant error about Pubnub

### ISSUE THREAD

**Issue by 3ne** [balansse/homebridge-vivint#19]
2/5/2021, 2:32:23 PM [Vivint] Reconnected to Pubnub
2/5/2021, 2:33:41 PM [Vivint] Could not connect to Pubnub, reconnecting...
2/5/2021, 2:33:41 PM [Vivint] {
  error: true,
  operation: 'PNSubscribeOperation',
  errorData: Error: socket hang up
      at connResetException (internal/errors.js:617:14)
      at TLSSocket.socketOnEnd (_http_client.js:493:23)
      at TLSSocket.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'ECONNRESET',
    response: undefined
  },
  category: 'PNNetworkIssuesCategory'
}

**Comment by balansse** [comment]
This can be caused by multiple reasons. Could you please restart your server and try again? Also, Node.JS might need to be updated.

**Comment by 3ne** [comment]
Restarted multiple times. This has happened on previous versions of the Vivint plugin but never this bad.

Pi3 model B
HOOBS 3.3.2/Raspbian 10 (buster)
Node 14.15.1

**Comment by balansse** [comment]
Do you still receive status updates for Vivint devices in HomeKit? If PubNub is completely not working you won't be able to receive any updates from Vivint.

**Comment by 3ne** [comment]
I receive updates in Homekit. The error had me concerned in case it was an indication of an issue that may have killed the Homekit updates.

**Comment by balansse** [comment]
The PubNub library will always try to reconnect in case of a failure like this, so eventually, you should see "Reconnected to Pubnub" in the log. These 'socket hang up' errors are out of control of the plugin - most probable cause is the connectivity issues between the HomeBridge and PubNub servers.

**Comment by 3ne** [comment]
Yes it does indicate reconnected to Pubnub. Thank you very much for the clarification, appreciate all the work you have put into this.

**Comment by jcharnet** [comment]
Hello. I've been using this plugin for over a year, and it's absolutely AMAZING! Congrats on all the work.
Since the latest upgrade to homebridge 1.4.0, I started noticing that my automation that turns on the backyard light if it's at night and the patio doors was opened, started failing. The door sensors are coming from vivint, and the lights from a normal HomeKit device. I checked the logs, and starting seeing a bunch of the Pubnub reconnecting:


`[02/02/2022, 16:11:52] [@balansse/homebridge-vivint] Could not connect to Pubnub, reconnecting...
[02/02/2022, 16:11:52] [@balansse/homebridge-vivint] {
  error: true,
  operation: 'PNSubscribeOperation',
  errorData: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read',
    response: undefined
  },
  category: 'PNNetworkIssuesCategory'
}`


Did something change recently in the plugin? I'm on 1.6.0 of the homebridge-vivint version.

Thank you so much.

**Comment by jgrimard** [comment]
That's the error I get when I reboot my router and lose Internet connection. Maybe your homebridge device is having issues with its Internet connection?

**Comment by jcharnet** [comment]
That is a good point, my homebridge is isntalled on a raspberry pi, and it's connected through ethernet and not wifi. I don't see any other device disconnecting from the internet, so I would assume my internet connection is fine. Now maybe my raspberry pi could be losing internet connection, I'll try to test that piece. Thanks for the tips.
