### ISSUE TITLE
Doorbell Cam "sensors" don't work and doorbell press 

### ISSUE THREAD

**Issue by ShibbyBro** [balansse/homebridge-vivint#21]
Hey so I'm trying to figure out if there's a way to make the doorbell actually send an alert to my phone/Apple TV or even trigger when it see's motion. Doesn't seem to be working at all. I can manually trigger this and it works. But that defeats the purpose.

**Comment by balansse** [comment]
Currently it is done via the http automation built in ffmpeg-camera plugin. I am currently working on a big update that will natively bring cameras and doorbells to HomeKit without requiring a separate plugin - it will be much easier to use! Stay tuned!

**Comment by ShibbyBro** [comment]
ok I'm actually using the that ffmpeg camera plugin and it still hasn't been able to send me alerts without me manually setting off the trigger. But that's great news that it'll work natively. When about are you thinking about releasing it?

**Comment by balansse** [comment]
I am preparing it for release now, should be live in a couple of days!

**Comment by j0np** [comment]
Any update when the new version will be released? Excited as I'm having odd issues with motion sensor and FFmpeg. My exterior camera doesn't notify on motion but doorbell can does..

**Comment by balansse** [comment]
I just released 1.5.0, please check it out and let me know!

**Comment by robfrizzy** [comment]
I had my cameras set up in ffmpeg and they were working fine. Saw the new update added native support for them, so I deleted the ffmpeg plugin. My doorbell camera is working fine. My other exterior camera is not. It shows a preview image, but when I try to view the camera feed it tries to connect but eventually fails. I had a similar problem with this camera with ffmpeg and I was able to fix it by disabling the audio feed for the camera in ffmpeg. This camera doesn’t have a microphone and I believe ffmpeg trying to get the audio stream and failing to do so was why it was getting hung up. I believe this is the case with what is happening with the native plug-in. It appears that it’s trying to get an audio feed from the camera (there’s a volume indicator on the top right of the window when trying to view the camera) but since the camera does nit have an audio feed, it fails.

**Comment by balansse** [comment]
Thank you for the feedback! 

Unfortunately, the only Vivint camera I own is a DBC300 doorbell which I used during the internal testing. It will help me a lot if you can run Homebridge in Debug mode and send me the log file from the moment Homebridge starts to the moment you clicked on the camera in Home app.

**Comment by balansse** [comment]
Please email it to me at balansse@gmail.com and I will check it out! Thank
you!

**Comment by balansse** [comment]
Please update to the latest version 1.5.1 and let me know if you still have issues with the cameras!

**Comment by robfrizzy** [comment]
It’s solved my problem with my camera with no audio. They’re working now. Thanks!

**Comment by catsartcox** [comment]
Just wanted to say thanks @balansse for all of your work on this.  Been using home bridge for years and years now and your fork on the Vivint stuff has been brilliant. The camera’s took so long to load in ffmpeg, but with your camera addition it works so quick.
