### ISSUE TITLE
Vivint accessories not showing up

### ISSUE THREAD

**Issue by jcdelacruz23** [balansse/homebridge-vivint#51]
Just installed the new 1.6.0 update. And my Vivint Devices still not showing up my hoobs accessory dashboard and HomeKit App.

**Comment by cptgreedle** [comment]
I'm having the exact same problem. I can't get it to show anything in HOOBS. Very frustrating!

**Comment by jgrimard** [comment]
Were you able to successfully login using the instructions here https://github.com/balansse/homebridge-vivint/issues/48#issuecomment-925844829 ?

**Comment by cptgreedle** [comment]
Yes! That did it! It was not easy though.

For those running HOOBS using the Hoobs desktop app (doesn't work on a mobile device from what I saw) you have to click on the  3 dots in the upper right corner, and select "Terminal". If you don't see it try a different device.
In terminal, you have to use the default hoobs login (if you haven't changed it), which is username "hoobs" and password "hoobsadmin". I had to do this even though my HOOBS account does not use this. From there you have to find the proper directory, mine was not the one they list on that page. I had to type `cd /var/lib/hoobs/homekit/nodemodules/@balansse/homebridge-vivint` where homekit was the name of the bridge. If you get a director missing error, type `cd /var/lib/hoobs` and then `ls -alhF` to see all the directories and files, and find the proper path that works for your setup.
Then I had to type `npm run mfa`. I then had to put in my vivint credentials, and when it asked me for the MFA, I had to go to the authenticator app I set up for my multifactor authentication (for me the new iOS15 authenticator worked perfectly), type in the code, and it told me to type a very long code into my refresh token for the app. I took a picture of it (because copy paste didn't work for me) and typed it into the refresh token and it all worked!
It is a long process, I had to do some trial and error, but it did actually work! Thanks for the suggestion.

**Comment by jgrimard** [comment]
@cptgreedle 
I have opened an issue in HOOBS if you want to voice your support of this request.  The HOOBS team needs to create a sidecar on their end to support the MFA custom UI.  https://github.com/hoobs-org/sidecars/issues/4

**Comment by robbhudson** [comment]
This has been REALLY helpful, thanks everyone (I'm new here). Just checking, when I see this in the Advanced area of the configuration, I'm done, right?

<img width="572" alt="Screen Shot 2021-09-29 at 11 06 17 AM" src="https://user-images.githubusercontent.com/63021758/135296743-63ded210-7e8a-4213-a48d-a4c3b0e9a27c.png">

how long should it take for the accessories to pop up?

**Comment by jgrimard** [comment]
@robbhudson 
Yes, include the s=  in the refresh token.
You will need to save the configuration and restart Homebridge for the settings to take affect.  Your accessories should pop up immediately after restarting.

**Comment by robbhudson** [comment]
Got it, and it is working. thank you!

**Comment by jgrimard** [comment]
This has been fixed in HOOBS 4.1.13. Please update your HOOBS to the latest version. You might also need to re-install the homebridge-vivint plugin. This issue can be closed.
